'use client';

import Image from 'next/image'
import chair from '@/public/images/chair.png'
import { Metadata } from 'next'
// import HeavyComponent from './components/HeavyComponent'
import { useState } from 'react';
import dynamic from 'next/dynamic';
// const HeavyComponent = dynamic(
//   () => import('./components/HeavyComponent'),
//   { loading: () => <p>Loading...</p> });
// import _ from 'lodash';

export default function Home() {

  return (
    <main className='relative h-screen'>
      <h1>Next.js</h1>
      <button onClick={async () => {
        const _ = (await import('lodash')).default;
        const users = [
          { name: 'c' },
          { name: 'b' },
          { name: 'a' }
        ];

        const sortedUsers = _.orderBy(users, ['name']);
        console.log(sortedUsers);

      }}>Show</button>
      {/* <Image 
        src="https://bit.ly/react-cover" 
        alt="Barber Chair" 
        fill
        className='object-cover'
        sizes="( max-width: 480px ) 100vw, ( max-width: 768px ) 50vw, 33vw"
        quality={100}
        priority
        /> */}
    </main>
  )
}

// export const metadata: Metadata = {
//   title: 'Next.js',
//   description: 'Generated by create next app',
// }